import esbuild from "esbuild";
import process from "process";
import fs from "fs/promises";
import path from "path";
import builtins from "builtin-modules";
import 'dotenv/config';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const vaultPluginPath = process.env.OBSIDIAN_PLUGIN_PATH;

if (!vaultPluginPath) {
  console.error("❌ Error: OBSIDIAN_PLUGIN_PATH environment variable is not set.");
  console.error("   Please create a .env file with OBSIDIAN_PLUGIN_PATH=<your vault path>");
  process.exit(1);
}

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    // CodeMirror 6 패키지들을 external로 추가
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    // Lezer 파서 관련
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    // Node.js 내장 모듈
    ...builtins
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: `${vaultPluginPath}/main.js`,
  platform: 'node',
  define: {
    'process.env.OPENAI_API_KEY': JSON.stringify(process.env.OPENAI_API_KEY)
  }
});

/**
 * 정적 파일을 Vault 플러그인 폴더로 복사
 */
async function copyStaticFiles() {
  const filesToCopy = [
    { src: "manifest.json", dest: "manifest.json", required: true },
    { src: "src/styles.css", dest: "styles.css", required: false }
  ];

  for (const file of filesToCopy) {
    try {
      const destPath = path.join(vaultPluginPath, file.dest);
      await fs.copyFile(file.src, destPath);
      console.log(`✅ Copied: ${file.src} → ${file.dest}`);
    } catch (error) {
      if (error.code === 'ENOENT') {
        if (file.required) {
          console.error(`❌ Required file missing: ${file.src}`);
          process.exit(1);
        } else {
          console.warn(`⚠️  Optional file not found: ${file.src} (skipping)`);
        }
      } else {
        console.error(`❌ Error copying ${file.src}:`, error.message);
        if (file.required) process.exit(1);
      }
    }
  }
}


if (prod) {
  // Production 빌드
  await context.rebuild();
  await copyStaticFiles();
  console.log("✅ Production build complete.");
  await context.dispose();
} else {
  // Development watch 모드
  await context.rebuild();
  await copyStaticFiles();
  
  await context.watch();
  console.log("👀 Watching for changes...");
}